version: 3

tasks:
  tailwind-gen:
    dir: ./
    cmds:
      - |
        npx @tailwindcss/cli \
          -i "./src/Palettes.App/Palettes.App/Styles/app.css" \
          -o "./src/Palettes.App/Palettes.App/wwwroot/css/app.css"
